### PR TITLE
Add organs plural

### PR DESCRIPTION
**Pull request by VedderPlet**

### CODE REVIEW

**Comment by mvasilkov** [comment]
Lol, man, this isn't even my repo :) you should've sent pull requests to the upstream.

**Comment by VedderPlet** [comment]
Omg D: does this mean you aren't going to the sadie Hawkins dance with me

**Comment by mvasilkov** [comment]
I'm atrocious at dancing, sadly.

**Comment by VedderPlet** [comment]
">I don't have an ethnicity"
Oh ok

**Pull request closed without merging**
